name: RunTests

on:
  push:
    branches:
    - master
    - develop/*
    - feature/*

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Print pwd && ls
      run: pwd && ls -la
    - name: Run go test for all packages
      env:
        marvel_api_key: ${{ secrets.marvelAPIKey }}
        marvel_api_hash: ${{ secrets.marvelHash }}
      run: go test ./... -v
    