name: RunTests

on:
  push:
    branches:
    - master
    - develop/*
    - feature/*

jobs:
  test:
    name: Run tests
    env:
      super_secret: ${{ secrets.testCaseSecret }}
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run go test for all packages
      run: go test ./test -v
    